// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhP4MIbDg9IFcvFpaVVi-QCaBPaG7RMcs',
    appId: '1:61102249759:web:51586f98b2a0bce583c22a',
    messagingSenderId: '61102249759',
    projectId: 'app1xbet1',
    authDomain: 'app1xbet1.firebaseapp.com',
    storageBucket: 'app1xbet1.firebasestorage.app',
    measurementId: 'G-11DM8JG7N4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjGQqzXCXR1RBYSkZr0cglt0WXrRXdA5E',
    appId: '1:61102249759:android:0798f5ca594ff77583c22a',
    messagingSenderId: '61102249759',
    projectId: 'app1xbet1',
    storageBucket: 'app1xbet1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4rD5-kimnUUflnMZGpU76OQkAmhA6xpU',
    appId: '1:61102249759:ios:ea9614dc3ef2d45183c22a',
    messagingSenderId: '61102249759',
    projectId: 'app1xbet1',
    storageBucket: 'app1xbet1.firebasestorage.app',
    androidClientId: '61102249759-5b76ghne00t7egtj0qettc83a6sb7fgn.apps.googleusercontent.com',
    iosClientId: '61102249759-0mrsls341tmvm67fjdn4g3vim6oecbr8.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4rD5-kimnUUflnMZGpU76OQkAmhA6xpU',
    appId: '1:61102249759:ios:ea9614dc3ef2d45183c22a',
    messagingSenderId: '61102249759',
    projectId: 'app1xbet1',
    storageBucket: 'app1xbet1.firebasestorage.app',
    androidClientId: '61102249759-5b76ghne00t7egtj0qettc83a6sb7fgn.apps.googleusercontent.com',
    iosClientId: '61102249759-0mrsls341tmvm67fjdn4g3vim6oecbr8.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhP4MIbDg9IFcvFpaVVi-QCaBPaG7RMcs',
    appId: '1:61102249759:web:3d3aa4669d8f0e9783c22a',
    messagingSenderId: '61102249759',
    projectId: 'app1xbet1',
    authDomain: 'app1xbet1.firebaseapp.com',
    storageBucket: 'app1xbet1.firebasestorage.app',
    measurementId: 'G-W6T5HNMETV',
  );
}
